name: wrap_maze
description: Wrap Maze - Tam özellikli labirent bulmaca oyunu
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State yönetimi
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Yerel veritabanı
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.3

  # Animasyon
  flutter_animate: ^4.5.0

  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  firebase_database: ^10.5.7      # Multiplayer realtime

  # Google Play Games
  games_services: ^4.0.1

  # In-App Purchase
  in_app_purchase: ^3.2.0
  in_app_purchase_android: ^0.3.5

  # Genel
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  uuid: ^4.4.2
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
