// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9Dip51PpuoieyNJhnCXGrAqMN73B4sig',
    appId: '1:105292792236:web:7a8a22ffe224fd76e83a09',
    messagingSenderId: '105292792236',
    projectId: 'wrap-maze',
    authDomain: 'wrap-maze.firebaseapp.com',
    databaseURL:
        'https://wrap-maze-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'wrap-maze.firebasestorage.app',
    measurementId: 'G-28E21X68K6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjoOOqJb_YtF5EoFwf_Tzj8KSX4r6aFXw',
    appId: '1:105292792236:android:0acb63e759bb11ace83a09',
    messagingSenderId: '105292792236',
    projectId: 'wrap-maze',
    databaseURL:
        'https://wrap-maze-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'wrap-maze.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBthsdASIaECyrkB2INX8ZKDbhWdjj1EAI',
    appId: '1:105292792236:ios:9d36b9c6400ec50de83a09',
    messagingSenderId: '105292792236',
    projectId: 'wrap-maze',
    databaseURL:
        'https://wrap-maze-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'wrap-maze.firebasestorage.app',
    iosBundleId: 'com.wrapmaze.game',
  );
}
